import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const mulish = Mulish()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={mulish.className}>
      <body>{children}</body>
    </html>
  )
}
